sudo: false
cache:
  directories:
    - $HOME/.yarn-cache
language: node_js
node_js: stable
os:
  - osx
branches:
  only:
    - master # build master branch only
install:
  - npm install
script:
  - npm run build